### ISSUE TITLE
No bias

### ISSUE THREAD

**Issue by shanefeng123** [eth-sri/lamp#2]
Hi,

In the supplementary materials of your paper where you discussed the threat model, you mentioned that "The model’s transformer blocks contain no bias terms". Do you mean that all the bias terms are removed, or they are not updated so that they don't have gradients? Also, does "transformer blocks" mean all the Linear layers in the encoder blocks? Or do you also include the LayerNorm layers and the last pooling layer?

Thanks, 
Shane

**Comment by dimy93** [comment]
Hi Shane, 
The point we make in the appendix is that LAMP is applicable even if those biases are not present in the model. However, we have not tested LAMP under these circumstances. Hopes this clarifies the issue.
Thanks,
Dimitar

**Comment by shanefeng123** [comment]
Hi Dimitar,

Thanks. It's very clear to me now.

Best,
Shane
